services:
  ***tracker:
    container_name: ***tracker
    image: ahobsonsayers/***tracker
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      UNTAPPD_COOKIE: ${UNTAPPD_COOKIE:-}
    volumes:
      - ./data:/app/data
