services:
  untrakkd:
    container_name: untrakkd
    image: ahobsonsayers/untrakkd
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      UNTAPPD_COOKIE: ${UNTAPPD_COOKIE:-}
      UNTAPPD_PROFILE: ${UNTAPPD_PROFILE:-}
    volumes:
      - ./data:/app/data