# Docs: https://taskfile.dev/#/usage
version: "3"

tasks:
  install:
    cmds:
      - uv sync

  format:
    cmds:
      - uv run ruff format .

  lint:
    cmds:
      - uv run ruff check --fix .
      - uv run ty check .

  test:
    cmds:
      - uv run pytest .

  build:
    cmds:
      - uv build

  run:
    cmds:
      - uv run untrakkd {{.CLI_ARGS}}

  run:fetch:
    cmds:
      - uv run untrakkd fetch

  run:server:
    cmds:
      - uv run untrakkd serve {{.CLI_ARGS}}

  docker:build:
    cmds:
      - docker build . --tag untrakkd

  docker:run:
    cmds:
      - docker compose up --build
