name: Build & Push Docker Image

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build & Push
    uses: ahobsonsayers/github-workflows/.github/workflows/docker-build-push.yaml@main
    secrets: inherit
    with:
      image-registry: ghcr.io
      image-name: ahobsonsayers/***tracker
      image-tags: latest
